### ISSUE TITLE
How to register for hopin events

### ISSUE THREAD

**Issue by ankitabantey** [WEHack-UTD2-0/wehack-utd2-0.github.io#19]

**Comment by Neha-Rode** [comment]
**Sessions**
- sessions can have a maximum of 4 tags
- each event has a max of 50 tags
- can record sessions w/ upgraded account
- session can have up to 20 participants
- invite only: only share audio/video by invite
- anyone can view
- priority num can be used for scheduling
- sessions run entirety of event (Can be added and deleted)

**Expo**
- booths can be mini, small, medium, large and also have priorities (can give higher tier sponsors larger booths)
- booths can be linked to sessions for real-time zoom-like capabilities

**Comment by Neha-Rode** [comment]
**ISSUES:**
****Hopin has a steep learning curve.****

**SUGGESTIONS/IDEAS**
- Have people on standby in discord voice channels to help people navigate Hopin
- Use event chat to direct people around
- Also direct people around in discord if they hate themselves and dont wanna stay in one place
- Keep video calling in Hopin instead of youtube livestream
